// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC96ursQFaEm9JIhFq1QX1MpnKXIxXDbcI',
    appId: '1:1002253291138:web:0ef4c7c89907629f822e9b',
    messagingSenderId: '1002253291138',
    projectId: 'auth-flutter-8a677',
    authDomain: 'auth-flutter-8a677.firebaseapp.com',
    storageBucket: 'auth-flutter-8a677.appspot.com',
    measurementId: 'G-FYEMWJ7C4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4_b1Dfydw6h7bXY5MY609nXC6F7-WAsU',
    appId: '1:1002253291138:android:8bfaec9959e92eab822e9b',
    messagingSenderId: '1002253291138',
    projectId: 'auth-flutter-8a677',
    storageBucket: 'auth-flutter-8a677.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC96ursQFaEm9JIhFq1QX1MpnKXIxXDbcI',
    appId: '1:1002253291138:web:9e446d7a6c3d492f822e9b',
    messagingSenderId: '1002253291138',
    projectId: 'auth-flutter-8a677',
    authDomain: 'auth-flutter-8a677.firebaseapp.com',
    storageBucket: 'auth-flutter-8a677.appspot.com',
    measurementId: 'G-3W9NN6FW9G',
  );
}
